fastlane_version "2.62.0"

default_platform :ios

platform :ios do

  ENV['FASTLANE_XCODEBUILD_SETTINGS_TIMEOUT'] = '60'
  ENV['FASTLANE_XCODEBUILD_SETTINGS_RETRIES'] = '10'

  desc "Upload an release ipa to TestFilght"
  lane :qw_release do |op|

      upload_ipa_to_testfltght(
        release: true,
        pod_install: op[:pod_install],
        version: op[:version],
        ipa_out_put_dir: op[:ipa_out_put_dir],
        scheme_name: op[:scheme_name],
        auto_increment_version: op[:auto_increment_version]
      )
   
  end

  desc "Upload an debug ipa to TestFilght"
  lane :qw_debug do |op|

      upload_ipa_to_testfltght(
        release: true,
        pod_install: op[:pod_install],
        version: op[:version],
        ipa_out_put_dir: op[:ipa_out_put_dir],
        scheme_name: op[:scheme_name],
        auto_increment_version: op[:auto_increment_version],
        build_num: op[:build_num]
      )
     
  end

  lane :upload_ipa_to_testfltght do |op|
      
      puts "#{op[:build_num]}"
      puts "#{op[:auto_increment_version]}"
      puts "#{op[:release]}"
      puts "#{op[:pod_install]}"
      puts "#{op[:version]}"
      puts "#{op[:scheme_name]}"
      puts "#{op[:ipa_out_put_dir]}"
      puts "@@@@@@@@@@@@@@@@@@@@@@@"
      is_release = op[:release]

      cocoapods if op[:pod_install]
 
      version_number = verify_version_lane version:op[:version]                  

      unless Dir.exist?(File.expand_path("#{out_put_dir}"))
          UI.error("#{out_put_dir} 路径不存在，请填写正确的打包路径")   
          next
      end 

      version_number = get_version_number  unless version_number
    
      String.include(VersionFactory)
      #补齐A.B.C格式
      version_number = version_number.formatABC
      version_number = version_number.increment if op[:auto_increment_version]
      puts "version_number:#{version_number}"
      version_number = increment_version_number(version_number: version_number)

      build_number = op[:build_num]
      unless op[:auto_increment_version] && op[:version] && build_number
        # if version number not be givend and can not auto increment then auto increment build number
        # build number not be givend       
        build_number = get_build_number 
        String.include(BuildNumberFactory)        
        build_number = build_number.formatABC
        build_number = build_number.incrementBuild        
      end

      build_number.is_build_avalable
      puts "build_number:#{build_number}"
      increment_build_number(build_number: build_number)
      
            
      #out ipa file path
      out_put_dir = verify_ipa_out_put_dir_lane  ipa_out_put_dir:op[:ipa_out_put_dir]
      sub_dir_name = is_release ? "release" : "debugBeta"
      full_output_dir = "#{out_put_dir}/#{sub_dir_name}"

      Dir.mkdir(File.expand_path("#{full_output_dir}")) unless Dir.exist?(File.expand_path("#{full_output_dir}"))

      out_ipa_name = is_release ? "release_#{version_number}_build_#{build_number}" : "debugBeta_#{version_number}_build_#{build_number}"

      gym_configuration = is_release ? "Release" : "Debug"

      scheme_name = verify_shceme_lane scheme_name:op[:scheme_name]
      # puts "scheme_name:#{scheme_name}"
      gym(
        scheme: scheme_name,
        output_directory: full_output_dir,
        silent: true,
        clean: false,
        configuration: gym_configuration,
        output_name: out_ipa_name,
        # export_xcargs: "-allowProvisioningUpdates",
      ) 
      pilot(
        ipa:"#{full_output_dir}/#{out_ipa_name}.ipa"
      ) 
  end 

  desc "检测version参数,不存在时就提示"
  lane :verify_version_lane do |options|
    
      unless options[:version]
        UI.message " ************************************************
         *  ⏰ 您未输入ipa的版本，将自动根据项目version进行自增
         *  您可以通过传入version来指定生成特定的版本号
         *  比如: fastlane release version:1.0.0   
         ************************************************"
      end
      options[:version]
  end

  desc "检测scheme，不存在时提示可设置"
  lane :verify_shceme_lane do |options|
      unless options[:scheme_name]
          UI.message " ************************************************
         *  ⏰ 您未指定特定的scheme,系统XcoudeBulid 将列出所有scheme让你选择
         *  您可以通过传入scheme_name来指定shceme
         *  比如: fastlane release scheme_name:\"cloudIM\" 
         ************************************************"
      end
      options[:scheme_name]
  end
  desc "检测ipa打包路径，未设置时，要求输入路径"
  lane :verify_ipa_out_put_dir_lane do |options|
       unless options[:ipa_out_put_dir]
        UI.message " ************************************************
         *  ❌ 未设定ipa打包路径,必须设定一个当前的ipa打包路径，否则ipa将打出在当前项目路径
         *  您可以通过传入ipa_out_put_dir来指定路径
         *  比如: fastlane release ipa_out_put_dir:\"~/desketop/打包\"   
         ************************************************"
        options[:ipa_out_put_dir] = UI.input("请输入打包路径:")
      end
      options[:ipa_out_put_dir]
  end

end


module BuildNumberFactory
  
  def is_build_avalable
      unless self =~ /^\d{1,}$/
          puts "build_number格式不对，正确格式应该为整数"
      end
  end
  
  def formatBuildNumber
      build_arrs = self.split('.').map(&:to_i);
      build_number = build_arrs.last;
      build_number = 0 unless build_number;
  end

  def incrementBuild
      build_arrs = self.split('.').map(&:to_i);
      build_number = build_arrs.last;
      if build_number
        build_number++
      else
        build_number = 0
      end

      build_number
  end
  
end

# 指定给String实例
module VersionFactory

def is_available

  unless self =~ /^\d{1,}.\d.\d$/
    puts "version_number格式不对，正确格式应该为 A.B.C "
    return false
  end
  true  
end

# 满足／^\d{1,}*／的值格式成 A.B.C的形式
def formatABC

  version_arrs = self.split('.')
  
  version_arrs << "0" if version_arrs.count == 1
  version_arrs << "0" if version_arrs.count == 2

  temp_version_number = version_arrs[0..2].join('.')


end


# self.split('.').join('').to_i + 1
#丑大了！！！,其实👇下面的方法和这一句代码效果一样，self.split('.').join('').to_i + 1 坑啊，写了那么多

# 将满足正则/^\d{1,}.\d.\d$/ 的值进行自增1
def increment

  version_arrs = self.split('.').map(&:to_i)

  if self =~ /^\d{1,}.[0-8].9$|^\d{1,}.[0-8].\d{2,}$/
  
     version_arrs[1] = version_arrs[1] + 1
     version_arrs[2] = 0
  
  elsif self =~ /^\d{1,}.9.9$|\d{1,}.\d{2,}.\d{2,}$/
     
     version_arrs[0] = version_arrs[0] + 1
     version_arrs[1] = 0
     version_arrs[2] = 0

  else

      version_arrs[2] = version_arrs[2] + 1

  end

  version_arrs[0..2].join('.')

end


end